version: '{build}'
shallow_clone: true
clone_depth: 1
init:
- git config --global core.autocrlf input

environment:
  matrix:
    - QT5: C:\Qt\5.6\msvc2015_64
      PLATFORM: X64
      SPEC: win32-msvc2015
      VSVER: 14
    - QT5: C:\Qt\5.7\msvc2015_64
      PLATFORM: X64
      SPEC: win32-msvc2015
      VSVER: 14
    - QT5: C:\Qt\5.8\msvc2015_64
      PLATFORM: X64
      SPEC: win32-msvc2015
      VSVER: 14



before_build:
  - set PATH=C:\cygwin\bin;%QT5%\bin;%PATH%
  - appveyor DownloadFile http://download.qt.io/official_releases/jom/jom.zip
  - 7z x -y jom.zip jom.exe

build:

build_script:
  - ps: $env:VSCOMNTOOLS=(Get-Content ("env:VS" + "$env:VSVER" + "0COMNTOOLS")) 
  - if "%PLATFORM%" == "X86" call "%VSCOMNTOOLS%\..\..\VC\vcvarsall.bat"
  - if "%PLATFORM%" == "X64" "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64
  - if "%PLATFORM%" == "X64" call "%VSCOMNTOOLS%\..\..\VC\vcvarsall.bat" x86_amd64
  - qmake -spec %SPEC% -r CONFIG+=debug_and_release CONFIG+=no_webkit qt_testability.pro
  - jom
