QT.gui_private.VERSION = 5.8.0
QT.gui_private.MAJOR_VERSION = 5
QT.gui_private.MINOR_VERSION = 8
QT.gui_private.PATCH_VERSION = 0
QT.gui_private.name = QtGui
QT.gui_private.module =
QT.gui_private.libs = $$QT_MODULE_LIB_BASE
QT.gui_private.includes = $$QT_MODULE_INCLUDE_BASE/QtGui/5.8.0 $$QT_MODULE_INCLUDE_BASE/QtGui/5.8.0/QtGui
QT.gui_private.frameworks =
QT.gui_private.depends = core_private gui
QT.gui_private.uses =
QT.gui_private.module_config = v2 internal_module
QT.gui_private.enabled_features = xcb accessibility-atspi-bridge evdev freetype system-freetype fontconfig gif harfbuzz ico jpeg linuxfb mtdev multiprocess png system-png system-xcb xcb-glx xcb-render xcb-sm xcb-xlib xinput2 xkbcommon-evdev xlib xrender
QT.gui_private.disabled_features = android-style-assets direct2d directfb egl egl_x11 eglfs eglfs_brcm eglfs_egldevice eglfs_gbm eglfs_mali eglfs_viv eglfs_viv_wl integrityfb libinput libinput-axis-api mirclient system-harfbuzz system-jpeg tslib xkb xkbcommon-system
QMAKE_LIBS_XCB = -lxcb
QMAKE_LIBS_FREETYPE = -lfreetype
QMAKE_INCDIR_FREETYPE = /usr/include/freetype2
QMAKE_LIBS_FONTCONFIG = -lfontconfig -lfreetype
QMAKE_INCDIR_FONTCONFIG = /usr/include/freetype2
QMAKE_LIBS_DRM = -ldrm
QMAKE_INCDIR_DRM = /usr/include/libdrm
QMAKE_LIBS_MTDEV = -lmtdev
QMAKE_LIBS_OPENGL = -lGL
QMAKE_INCDIR_OPENGL = /usr/include/libdrm
QMAKE_LIBS_LIBPNG = -lpng12
QMAKE_INCDIR_LIBPNG = /usr/include/libpng12
QMAKE_LIBS_XCB_SYSLIBS = -lxcb-sync -lxcb-xfixes -lxcb-render -lxcb-randr -lxcb-image -lxcb-shm -lxcb-keysyms -lxcb-icccm -lxcb-shape -lxcb
QMAKE_LIBS_XCB_GLX = -lxcb-glx -lxcb
QMAKE_LIBS_XCB_RENDER = -lxcb-render-util -lxcb-render -lxcb
QMAKE_LIBS_X11SM = -lSM -lICE
QMAKE_LIBS_XCB_XLIB = -lxcb -lX11 -lX11-xcb
QMAKE_LIBS_XINPUT2 = -lXi
QMAKE_LIBS_XKBCOMMON_EVDEV = -lxkbcommon
QMAKE_LIBS_XRENDER = -lXrender
